from . import test_absence
from . import test_absence_tour
from . import test_contact
from . import test_contact_group_change_tour
from . import test_contact_relation_wizard
from . import test_contact_tour
from . import test_course_transition
from . import test_course_transition_tour
from . import test_enrollment
from . import test_enrollment_benefit
from . import test_enrollment_template
from . import test_enrollment_placement
from . import test_exit_management
from . import test_level
from . import test_level_tour
from . import test_student_document
from . import test_student_document_tour
from . import test_student_google_workspace
from . import test_study
from . import test_study_tour
from . import test_subject
from . import test_subject_tour
from . import test_outcome
from . import test_outcome_tour
from . import test_criteria
from . import test_criteria_tour
from . import test_content
from . import test_content_tour
from . import test_course
from . import test_course_tour
from . import test_company_settings
from . import test_settings
from . import test_settings_tour
from . import test_employee_display_fields
from . import test_employee_archived_reason_tour
from . import test_employee_tour
from . import test_workgroup
from . import test_workgroup_tour
from . import test_job
from . import test_job_tour
from . import test_work_location_tour
from . import test_employment_type_tour
from . import test_strike_reason_tour
from . import test_schedule_framework_tour
from . import test_enrollment_items_tour
from . import test_enrollment_template_tour
from . import test_teaching
from . import test_teaching_tour
from . import test_tracking
from . import test_non_teaching_type_tour
from . import test_teaching_reduction_type_tour
from . import test_employee_autocheckout
from . import test_user_implied_groups
from . import test_space_type
from . import test_space_type_tour
from . import test_space
from . import test_space_tour
from . import test_group_tour
from . import test_attendance_template
from . import test_attendance_schedule
from . import test_attendance_status
from . import test_attendance_status_tour
from . import test_attendance_justification
from . import test_attendance_justification_tour
from . import test_employee_role_group_sync
from . import test_employee_photo_visibility
from . import test_attendance_correction
from . import test_attendance_correction_tour
from . import test_attendance_reports
from . import test_attendance_reports_tour
from . import test_attendance_issue_tour
from . import test_grade_session
from . import test_grade_import_wizard
from . import test_applicant_import_wizard
from . import test_applicant_import_wizard_tour
from . import test_student_import_wizard
from . import test_student_import_wizard_tour
from . import test_student_update_wizard
from . import test_student_update_wizard_tour
from . import test_planning
from . import test_portal_access_wizard
from . import test_portal_access_wizard_tour
from . import test_portal_enrollment
from . import test_data_custom_import_prefix
from . import test_data_main_cat_prefix
from . import test_security_group_references
from . import test_grade_session_tour
from . import test_grade_session_state_wizard_tour
from . import test_grade_import_wizard_tour
from . import test_employee_google_workspace
from . import test_employee_google_workspace_tour
from . import test_student_google_workspace_tour
from . import test_employee_ems_user
from . import test_strike
from . import test_strike_tour
from . import test_working_schedule
from . import test_ems_teaching_sync
from . import test_employee_schedule_lifecycle
from . import test_working_schedules_import_wizard
from . import test_working_schedules_import_wizard_tour
from . import test_working_schedule_split_period_tour
from . import test_working_schedule_stale_breaks_tour
from . import test_task_assignment
from . import test_year_record
from . import test_non_teaching_type
from . import test_teaching_reduction_type
from . import test_group
from . import test_group_classroom_change
from . import test_group_classroom_change_tour
from . import test_group_classroom_suggestion
from . import test_group_classroom_suggestion_tour
from . import test_group_schedule
from . import test_guard_duty_board
from . import test_guard_duty_board_tour
from . import test_em_grading_wizard
from . import test_department
from . import test_departure_reason
from . import test_company_director
from . import test_role
from . import test_role_color_tour
from . import test_department_color_tour
from . import test_department_head_optional_tour
from . import test_attendance_template_color_tour
from . import test_withdrawal_tour
from . import test_enrollment_header
from . import test_authorization
from . import test_authorization_template_tour
from . import test_attendance_notification_tour
from . import test_enrollment_collections_tour
from . import test_task_assignment_tour
from . import test_family_tour
from . import test_payment_term
from . import test_enrollment_line
from . import test_enrollment_tour
from . import test_enrollment_placement_tour
from . import test_enrollment_proposal_tour
from . import test_applicant_tour
from . import test_no_destination_tour
from . import test_year_record_tour
from . import test_planning_tour
from . import test_em_grading_wizard_tour
from . import test_provider_tour
from . import test_enrollment_config_tour
from . import test_limesurvey_recipient_tour
from . import test_limesurvey_header_tour
from . import test_attendance_correction_request_tour
from . import test_asp_tour
from . import test_portal_tour
from . import test_portal_actions
from . import test_enrollment_product_extension
from . import test_enrollment_mail_activity
from . import test_attendance_session
from . import test_attendance_session_tour
from . import test_attendance_passlist_tour
from . import test_attendance_template_tour
from . import test_attendance_archived_filter_tour
from . import test_attendance_issue
from . import test_strike_reason
from . import test_minute
from . import test_notice
from . import test_notice_tour
from . import test_limesurvey_api
from . import test_limesurvey_orchestration
from . import test_limesurvey_header
from . import test_limesurvey_recipient
from . import test_limesurvey_block_tour
from . import test_shared_mixins
from . import test_grade_matrix_tour
from . import test_grade_tutor_matrix_tour
from . import test_employee_staff_permissions
from . import test_employee_staff_permissions_tour
from . import test_student_data_reader
from . import test_student_data_reader_tour
from . import test_student_my_groups
from . import test_student_my_groups_tour
